"project_identifier" : CROWDIN_PROJECT_IDENTIFIER
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/default.pot",
  "dest": "/widgets/hub-project-team-widget/default.pot",
  "translation" : "/src/app/translations/hub-project-team-widget_%two_letters_code%.po",
 }
]
